### ISSUE TITLE
Fix: about post's likes error

### ISSUE THREAD

**Issue by JellyBear97** [songhsb/triptoday#22]
- error description : detail post 불러올 때, db.json에 해당 게시물에 대한 likes 정보가 없으면 post id 를 기반으로 likes collection의 id값이 정해져야하는 것이 맞습니다. 기능 구현시 최초 likes collection을 생성할 때 만들어주는 객체에 likes id값으로 들어갈 id(postId)없이 {userList : []} 만을 저장한 탓에 likes 조회시 id값이 맞지 않아 오류가 발생했었습니다! 수정했고, 정상작동 되니, 본인 코드에 반영이 되었는지 확인 후 꼭 수정 부탁드립니다. 확인 후 댓글로 체크 부탁드립니당
- error correction location : src > Detail > LikesPosts.jsx => 44번째 줄 근방
- error correction content : {userList : []} → { id: postId, userList: [], }

**Comment by songhsb** [comment]
네! 고친 후 정상작동 됩니다. 고생하셨습니다.
